version: '3.8'
services:
  database:
    image: mysql:8.0
    volumes:
      # if you are running linux or max, the host folder will likely be different :)
      - /c/dbplayground/mysql:/var/lib/mysql # persistent mysql database data.
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql