version: "3.8"
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /c/dbplayground/postgres:/var/lib/postgresql/data # persistent postgres database data.
    environment:
      - POSTGRES_PASSWORD=postgres
